image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build
  - deploy

build-prod:
  stage: build
  only:
    - prod
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk

build-dev:
  stage: build
  only:
    - dev
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk


dev-deploy:
  stage: deploy
  only:
    - dev
  image: vagsa2/appcenter-cli
  dependencies:
    - build-dev
  script:
    - appcenter distribute release
      --token $APPCENTER_ACCESS_TOKEN
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with dev version of sdk'
      --app "Contextual/Wikipedia-DevSDK-Prod-Wikipedia-1"
      --quiet

prod-deploy:
  stage: deploy
  only:
    - prod
  image: vagsa2/appcenter-cli
  script:
    - appcenter distribute release
      --token $APPCENTER_ACCESS_TOKEN
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with Prod version of sdk'
      --app "Contextual/Wikipedia-ProdSDK-Prod-Wikipedia-1"
      --quiet