stages:
  - build

dev:build:
  stage: build
  inherit:
    variables:
      - UPSTREAM_VERSION_NAME
  script:
    - echo "UPSTREAM VERSION -> ${UPSTREAM_VERSION_NAME}"
    - sh -x build.sh
  tags:
    - android
