
variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS:   "latest"
  COMMAND_LINE_TOOLS: "7583922"
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: release

stages:
  - build

dev:bison:build:
  stage: build
  only:
    refs:
      - dev-bison
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with dev version of sdk'
      --app "Pointzi/Wikipedia-Dev-Bison-PZDynamic_bison"
      --token "${APP_CENTER_TOKEN}"
      --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

dev:zebra:build:
  stage: build
  only:
    refs:
      - dev-zebra
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Zebra server with dev version of sdk'
      --app "Pointzi/Wikipedia-Dev-Zebra-PZDynamic_zebra"
      --token "${APP_CENTER_TOKEN}"
      --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

prod:bison:build:
  stage: build
  only:
    refs:
      - prod-bison
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with prod version of sdk'
      --app "Pointzi/Wikipedia-Prod-Bison-PZDynamic_bison"
      --token "${APP_CENTER_TOKEN}"
      --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

prod:zebra:build:
  stage: build
  only:
    refs:
      - prod-zebra
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Zebra server with prod version of sdk'
      --app "Pointzi/Wikipedia-Prod-Zebra-PZDynamic_zebra"
      --token "${APP_CENTER_TOKEN}"
      --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

prod:demo:build:
  stage: build
  only:
    refs:
      - prod-demo
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Zebra server with prod version of sdk'
      --app "Pointzi/Wikipedia-Prod-Bison-wikipedia_demo"
      --token "${APP_CENTER_TOKEN}"
      --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

