
variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS:   "latest"
  COMMAND_LINE_TOOLS: "7583922"
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: release

stages:
  - build

dev:bison:build:
  stage: build
  only:
    refs:
    - bison_dev
  script:
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assemble'
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/devBison/debug/app-devBison-debug.apk" \
        --release-notes 'Bison release with dev version of sdk' \
        --app "PZDynamic_bison" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/devBison/debug/app-devBison-debug.apk
    expire_in: 10 h

dev:zebra:build:
  stage: build
  only:
    refs:
    - zebra
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/debug/app-debug.apk" \
        --release-notes 'Bison release with dev version of sdk' \
        --app "Pointzi/Wikipedia-Dev-Bison-PZDynamic_bison" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

prod:bison:build:
  stage: build
  only:
    refs:
    - bison
  script:
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assemble'
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/prodBison/debug/app-prodBison-debug.apk" \
        --release-notes 'Bison release with release version of sdk' \
        --app "PZDynamic_bison" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodBison/debug/app-prodBison-debug.apk
    expire_in: 10 h

prod:zebra:build:
  stage: build
  only:
    refs:
    - zebra_prod
  script:
    - sed -i.bak 's/PZDynamic_bison/PZDynamic_zebra/g' app/src/main/AndroidManifest.xml
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assembleDebug'
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/prodZebra/app-prodZebra-debug.apk" \
        --release-notes 'Zebra release with release version of sdk' \
        --app "PZDynamic_zebra" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodZebra/debug/app-prodZebra-debug.apk
    expire_in: 10 h

prod:demo:build:
  stage: build
  only:
    refs:
    - demo
  script:
    - sed -i.bak 's/PZDynamic_bison/wikipedia_demo/g' app/src/main/AndroidManifest.xml
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assembleDebug'
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/prodDemo/app-prodDemo-debug.apk" \
        --release-notes 'Wikipedia release with release version of sdk' \
        --app "wikipedia_demo" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodDemo/debug/app-prodDemo-debug.apk
    expire_in: 10 h

