stages:
  - build

dev:build:
  stage: build
  inherit:
    variables:
      - UPSTREAM_VERSION_NAME
  script:
    - echo "VERSION_NAME=${UPSTREAM_VERSION_NAME}" >> local.properties
    - sh -x build.sh
  tags:
    - android
