
variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS:   "latest"
  COMMAND_LINE_TOOLS: "7583922"
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: release


stages:
  - build
  - upload

dev:bison:build:
  stage: build
  only:
    refs:
    - bison_dev
  script:
    - sed -i.bak 's/PZDynamic_bison/PZDynamic_zebra/g' app/src/main/AndroidManifest.xml
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assemble'
    - appcenter distribute release \
        --group Collaborators \
        --file "app/build/outputs/apk/devBison/debug/app-devBison-debug.apk" \
        --release-notes 'Bison release with dev version of sdk' \
        --app "PZDynamic_zebra" \
        --token "${APP_CENTER_TOKEN}" \
        --quiet
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/devBison/debug/app-devBison-debug.apk
    expire_in: 10 h

dev:zebra:build:
  stage: build
  only:
    refs:
    - zebra
  script:
    - sed -i.bak 's/PZDynamic_bison/PZDynamic_zebra/g' app/src/main/AndroidManifest.xml
    - docker run -v $PWD:/build/ -t androidsdk/android-30:latest bash -c 'cd /build; ./gradlew assembleDebug'
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 10 h

prod:bison:build:
  stage: build
  only:
    refs:
    - bison
  script:
    - ./gradlew --refresh-dependencies --stacktrace assembleProdBisonDebug
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodBison/debug/app-prodBison-debug.apk
    expire_in: 10 h

prod:zebra:build:
  stage: build
  only:
    refs:
    - zebra_prod
  script:
    - ./gradlew --refresh-dependencies --stacktrace assembleProdZebraDebug
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodZebra/debug/app-prodZebra-debug.apk
    expire_in: 10 h

prod:demo:build:
  stage: build
  only:
    refs:
    - demo
  script:
    - ./gradlew --refresh-dependencies --stacktrace assembleProdDemoDebug;
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodDemo/debug/app-prodDemo-debug.apk
    expire_in: 10 h

dev:bdd:build:
  stage: build
  only:
    refs:
    - bdd
  script:
    - ./gradlew --refresh-dependencies --stacktrace assembleProdDemoDebug;
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/apk/prodDemo/debug/app-prodDemo-debug.apk
    expire_in: 10 h

dev:bison:upload:
  stage: upload
  only:
    refs:
    - bison_dev
  script:
    - ./gradlew --stacktrace appCenterUploadDevBisonDebug
  tags:
    - android
  needs:
    - dev:bison:build

dev:zebra:upload:
  stage: upload
  only:
    refs:
    - zebra
  script:
    - appcenter distribute release
        --group Collaborators
        --file "app/build/outputs/apk/debug/app-debug.apk"
        --release-notes 'Zebra release with dev version of sdk'
        --app "Streethawk/.Wiki-Dev-PZDynamic_zebra"
        --token "${APP_CENTER_TOKEN}"
        --quiet
  tags:
    - android
  needs:
    - dev:zebra:build

dev:bdd:upload:
  stage: upload
  only:
    refs:
    - bdd
  script:
    - ./gradlew --stacktrace appCenterUploadDevBDDDebug
  tags:
    - android
  needs:
    - dev:bdd:build

prod:bison:upload:
  stage: upload
  only:
    refs:
    - bison
  script:
    - ./gradlew --stacktrace appCenterUploadProdBisonDebug
  tags:
    - android
  needs:
    - prod:bison:build

prod:zebra:upload:
  stage: upload
  only:
    refs:
    - zebra_prod
  script:
    - ./gradlew --stacktrace appCenterUploadProdZebraDebug
  tags:
    - android
  needs:
    - prod:zebra:build

prod:demo:upload:
  stage: upload
  only:
    refs:
    - demo
  script:
    - ./gradlew --stacktrace appCenterUploadProdDemoDebug
  tags:
    - android
  needs:
    - prod:demo:build

